- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HealthyHostCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: UnHealthyHostCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: RequestCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Average
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: TargetResponseTime
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Average
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTPCode_ELB_4XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTPCode_ELB_5XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_2XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_3XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_4XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_5XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: ActiveConnectionCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: NewConnectionCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: RequestCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: TargetResponseTime
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Average
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: TargetResponseTime
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Average
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: TargetResponseTime
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Average
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: ActiveConnectionCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: NewConnectionCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: RejectedConnectionCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: TargetConnectionErrorCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: RequestCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: IPv6RequestCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: RequestCountPerTarget
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: NonStickyRequestCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_2XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_3XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_4XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: HTTPCode_Target_5XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTPCode_ELB_3XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTPCode_ELB_4XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTPCode_ELB_5XX_Count
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTP_Fixed_Response_Count
  aws_namespace: AWS/ApplicationELB
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTP_Redirect_Count
  aws_namespace: AWS/ApplicationELB
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: HTTP_Redirect_Url_Limit_Exceeded_Count
  aws_namespace: AWS/ApplicationELB
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: ProcessedBytes
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: IPv6ProcessedBytes
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: ConsumedLCUs
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: ClientTLSNegotiationErrorCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - TargetGroup
  - LoadBalancer
  aws_metric_name: TargetTLSNegotiationErrorCount
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
- aws_dimensions:
  - LoadBalancer
  - TargetGroup
  aws_metric_name: RuleEvaluations
  aws_namespace: AWS/ApplicationELB
  aws_statistics:
  - Sum
