name: Python application

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test app
      env:
        LOGZIO_REGION: us
        AWS_NAMESPACES: AWS/EC2,AWS/Lambda,AWS/CloudFront,aws/wrong,AWS/nosuch
        LOGZIO_TOKEN: jusTaFaKeTOKEndmtQPilCqwerAAssPP
        AWS_DEFAULT_REGION: us-east-1
        SCRAPE_INTERVAL: 300
        P8S_LOGZIO_NAME: tests
      run: |
        python tests.py
